version: 2.1
executors:
  golang:
    docker:
      - image: beyondsecurity/golang
jobs:
  test:
    working_directory: ~/project
    executor: golang
    steps:
      - checkout
      - run: go test ./...

workflows:
  version: 2
  build:
    jobs:
      - test:
          context:
            - BuildContext
